### ISSUE TITLE
`datasets_builder` fails with a `FileExistsError` when labels are provided

### ISSUE THREAD

**Issue by ashuping** [sharc-lab/HLSFactory#1]
### Synopsis
When `datasets_builder` is called with `dataset_labels`, for example, in the [full_flow_xilinx](https://github.com/sharc-lab/HLSFactory/blob/main/demos/demo_full_flow_xilinx/full_flow_xilinx.ipynb) demo, the call fails with a `FileExistsError`.

### Cause
After looking through [the function](https://github.com/sharc-lab/HLSFactory/blob/de967ca99921d8df059dc3314b865a25578640a6/hlsfactory/datasets_builtin.py#L90), it seems like the error is caused by the interaction between two issues in the code. First, the dataset builders [(lines 34 through 77)](https://github.com/sharc-lab/HLSFactory/blob/de967ca99921d8df059dc3314b865a25578640a6/hlsfactory/datasets_builtin.py#L34-L77) do not take a provided label into account when creating the subdirectory of the working directory where the dataset should be copied. For example, in the [full_flow_xilinx demo](https://github.com/sharc-lab/HLSFactory/blob/de967ca99921d8df059dc3314b865a25578640a6/demos/demo_full_flow_xilinx/full_flow_xilinx.py#L42-L54), the call to `datasets_builder` is as follows:

```python
datasets = datasets_builder(
    WORK_DIR,
    [
        "polybench",
        "machsuite",
        "chstone",
    ],
    dataset_labels=[
        "polybench_xilinx",
        "machsuite_xilinx",
        "chstone_xilinx",
    ],
)
```

However, the folders within `work` are simply labeled `polybench`, `machsuite`, and `chstone`, rather than the user-provided labels `polybench_xilinx`, `machsuite_xilinx`, and `chstone_xilinx`.

The second issue is that, when labels are provided, each call to `dataset_builder` is actually run twice. Within `datasets_builder`, if dataset labels are provided, the program will run through the correct sequence to copy the appropriate dataset files into the working directory [(lines 96 through 111)](https://github.com/sharc-lab/HLSFactory/blob/de967ca99921d8df059dc3314b865a25578640a6/hlsfactory/datasets_builtin.py#L96-L111); however, it will then continue on and try to run the code for non-labeled datasets [(lines 113 through 122](https://github.com/sharc-lab/HLSFactory/blob/de967ca99921d8df059dc3314b865a25578640a6/hlsfactory/datasets_builtin.py#L113-L122). Since the directories have the same name regardless of label, the calls to `shutil.copy` within the individual dataset builders will see that a directory with the desired name already exists (since it was already created properly in the labeled-data part of the program) and return a `FileExistsError`.

### Test Case
The following test-case identifies the error:
```python
def test_load_datasets_with_labels() -> None:
    top_work_dir = get_work_dir()
    work_dir = top_work_dir / "test_load_datasets_with_labels"
    remove_and_make_new_dir_if_exists(work_dir)

    dataset_names = DATASET_STR_MAP
    dataset_labels = [f"{dset}_labeled" for dset in dataset_names]

    datasets = datasets_builder(
        work_dir,
        dataset_names,
        dataset_labels
    )

    assert str(datasets)
    assert datasets
```

### Solution
See [pull request](https://github.com/sharc-lab/HLSFactory/pull/2)

**Comment by stefanpie** [comment]
Wow you are our first issue and outside contributor! Thank you for the detailed issue and pull request.

I'll review the pull request, likely tonight, for merging. At first glance it look reasonable.

Definitely let us know if you have any other questions, help with a specific use case, or any gaps in our documentation that would be helpful to prioritize (we are still working to get docs in a more complete state). We also still have some more code cleanup and refactoring to do.

Thanks again!
